apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejsapp
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: nodejsapp
                port:
                  number: {{ .Values.service.port }}
            path: /