apiVersion: v1
kind: Service
metadata:
  name: nodejsapp
  namespace: {{ .Release.Namespace }}
  labels:
    {{ toYaml .Values.podLabels | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ toYaml .Values.podLabels | nindent 4 }}
